version: "3.5"

services:
  shortener:
    image: tna0y/linkshortener:latest
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      LS_BIND: ":8000"
      LS_BASE_URL: "http://localhost:8000"
      LS_BOT_TOKEN: "<TELEGRAM API TOKEN>"
      LS_POSTGRES_DSN: "<POSTGRES DSN>"

